# Generated by Django 6.0.5 on 2026-06-06 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnockoutRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('order', models.PositiveSmallIntegerField(help_text='1=Dieciseisavos, 2=Octavos...', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Fase eliminatoria',
                'verbose_name_plural': 'Fases eliminatorias',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Nombre')),
                ('teams', models.ManyToManyField(related_name='groups', to='matches.team', verbose_name='Equipos')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnockoutMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_home', models.CharField(blank=True, help_text='Ej: 1° Grupo A', max_length=50, verbose_name='Slot local')),
                ('slot_away', models.CharField(blank=True, help_text='Ej: 2° Grupo B', max_length=50, verbose_name='Slot visitante')),
                ('went_to_penalties', models.BooleanField(default=False, verbose_name='Fue a penales')),
                ('home_penalties', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Penales local')),
                ('away_penalties', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Penales visitante')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knockout_match', to='matches.match', verbose_name='Partido')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.knockoutround', verbose_name='Fase')),
            ],
            options={
                'verbose_name': 'Partido eliminatorio',
                'verbose_name_plural': 'Partidos eliminatorios',
            },
        ),
        migrations.CreateModel(
            name='GroupStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.PositiveSmallIntegerField(default=0, verbose_name='PJ')),
                ('won', models.PositiveSmallIntegerField(default=0, verbose_name='G')),
                ('drawn', models.PositiveSmallIntegerField(default=0, verbose_name='E')),
                ('lost', models.PositiveSmallIntegerField(default=0, verbose_name='P')),
                ('goals_for', models.PositiveSmallIntegerField(default=0, verbose_name='GF')),
                ('goals_against', models.PositiveSmallIntegerField(default=0, verbose_name='GC')),
                ('points', models.PositiveSmallIntegerField(default=0, verbose_name='Pts')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournament.group', verbose_name='Grupo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='matches.team', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Tabla de posiciones',
                'ordering': ['-points', '-won', 'goals_against'],
                'unique_together': {('group', 'team')},
            },
        ),
    ]
