# Generated by Django 6.0.5 on 2026-06-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knockoutmatch',
            options={'ordering': ['round__order', 'slot_number'], 'verbose_name': 'Partido eliminatorio', 'verbose_name_plural': 'Partidos eliminatorios'},
        ),
        migrations.AddField(
            model_name='knockoutmatch',
            name='slot_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='1=arriba, 2=abajo, 3=tercero... define el orden visual en el bracket', verbose_name='Posición en la llave'),
        ),
    ]
