# Generated by Django 6.0.5 on 2026-06-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='marketing_image',
            field=models.ImageField(blank=True, null=True, upload_to='leagues/marketing/', verbose_name='Marketing — imagen'),
        ),
        migrations.AddField(
            model_name='league',
            name='marketing_link_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marketing — texto del botón'),
        ),
        migrations.AddField(
            model_name='league',
            name='marketing_link_url',
            field=models.URLField(blank=True, verbose_name='Marketing — URL del botón'),
        ),
        migrations.AddField(
            model_name='league',
            name='marketing_text',
            field=models.TextField(blank=True, verbose_name='Marketing — texto'),
        ),
        migrations.AddField(
            model_name='league',
            name='marketing_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marketing — título'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_1_description',
            field=models.TextField(blank=True, verbose_name='Premio 1 — descripción'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='leagues/prizes/', verbose_name='Premio 1 — imagen'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_1_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Premio 1 — nombre'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_2_description',
            field=models.TextField(blank=True, verbose_name='Premio 2 — descripción'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='leagues/prizes/', verbose_name='Premio 2 — imagen'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_2_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Premio 2 — nombre'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_3_description',
            field=models.TextField(blank=True, verbose_name='Premio 3 — descripción'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_3_image',
            field=models.ImageField(blank=True, null=True, upload_to='leagues/prizes/', verbose_name='Premio 3 — imagen'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_3_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Premio 3 — nombre'),
        ),
        migrations.AddField(
            model_name='league',
            name='prizes_title',
            field=models.CharField(blank=True, default='Premios', max_length=100, verbose_name='Título sección premios'),
        ),
    ]
