# Generated by Django 6.0.5 on 2026-06-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_league_marketing_image_league_marketing_link_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='leagues/logos/', verbose_name='Logo de la liga'),
        ),
    ]
