# Generated by Django 6.0.5 on 2026-06-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_league_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='prize_4_description',
            field=models.TextField(blank=True, verbose_name='Premio 4 — descripción'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_4_image',
            field=models.ImageField(blank=True, null=True, upload_to='leagues/prizes/', verbose_name='Premio 4 — imagen'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_4_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Premio 4 — nombre'),
        ),
    ]
