# Generated by Django 6.0.5 on 2026-06-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_league_prize_4_description_league_prize_4_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='prize_10_description',
            field=models.TextField(blank=True, verbose_name='Premio 10 — descripción'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_10_image',
            field=models.ImageField(blank=True, null=True, upload_to='leagues/prizes/', verbose_name='Premio 10 — imagen'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_10_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Premio 10 — nombre'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_11_description',
            field=models.TextField(blank=True, verbose_name='Premio 11 — descripción'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_11_image',
            field=models.ImageField(blank=True, null=True, upload_to='leagues/prizes/', verbose_name='Premio 11 — imagen'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_11_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Premio 11 — nombre'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_12_description',
            field=models.TextField(blank=True, verbose_name='Premio 12 — descripción'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_12_image',
            field=models.ImageField(blank=True, null=True, upload_to='leagues/prizes/', verbose_name='Premio 12 — imagen'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_12_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Premio 12 — nombre'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_5_description',
            field=models.TextField(blank=True, verbose_name='Premio 5 — descripción'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_5_image',
            field=models.ImageField(blank=True, null=True, upload_to='leagues/prizes/', verbose_name='Premio 5 — imagen'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_5_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Premio 5 — nombre'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_6_description',
            field=models.TextField(blank=True, verbose_name='Premio 6 — descripción'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_6_image',
            field=models.ImageField(blank=True, null=True, upload_to='leagues/prizes/', verbose_name='Premio 6 — imagen'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_6_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Premio 6 — nombre'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_7_description',
            field=models.TextField(blank=True, verbose_name='Premio 7 — descripción'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_7_image',
            field=models.ImageField(blank=True, null=True, upload_to='leagues/prizes/', verbose_name='Premio 7 — imagen'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_7_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Premio 7 — nombre'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_8_description',
            field=models.TextField(blank=True, verbose_name='Premio 8 — descripción'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_8_image',
            field=models.ImageField(blank=True, null=True, upload_to='leagues/prizes/', verbose_name='Premio 8 — imagen'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_8_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Premio 8 — nombre'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_9_description',
            field=models.TextField(blank=True, verbose_name='Premio 9 — descripción'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_9_image',
            field=models.ImageField(blank=True, null=True, upload_to='leagues/prizes/', verbose_name='Premio 9 — imagen'),
        ),
        migrations.AddField(
            model_name='league',
            name='prize_9_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Premio 9 — nombre'),
        ),
        migrations.AddField(
            model_name='league',
            name='prizes_title2',
            field=models.CharField(blank=True, default='Premios Mundial Completo', max_length=100, verbose_name='Premios Mundial Completo'),
        ),
        migrations.AddField(
            model_name='league',
            name='prizes_title3',
            field=models.CharField(blank=True, default='Premios Resulatados partido de Argentina exacto', max_length=100, verbose_name='Premios Resulatados partido de Argentina exacto'),
        ),
        migrations.AlterField(
            model_name='league',
            name='prizes_title',
            field=models.CharField(blank=True, default='Premios Primera Ronda', max_length=100, verbose_name='Premios Primera Ronda'),
        ),
    ]
