# Generated by Django 6.0.5 on 2026-06-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_league_prize_10_description_league_prize_10_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='prizes_title3',
            field=models.CharField(blank=True, default='Premios Resultados Partido de Argentina exacto', max_length=100, verbose_name='Premios Resultados Partido de Argentina exacto'),
        ),
    ]
