# Generated by Django 6.0.5 on 2026-06-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_alter_league_prizes_title3'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='prizes_title4',
            field=models.CharField(blank=True, default='Premios Mundial Completo', max_length=100, verbose_name='Premios Mundial Completo'),
        ),
        migrations.AlterField(
            model_name='league',
            name='prizes_title2',
            field=models.CharField(blank=True, default='Premios Resultados Partido de Argentina', max_length=100, verbose_name='Premios Resultados Partido de Argentina'),
        ),
    ]
