# Generated by Django 6.0.5 on 2026-06-28 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_league_prizes_title4_alter_league_prizes_title2'),
        ('tournament', '0002_alter_knockoutmatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='start_from_round',
            field=models.ForeignKey(blank=True, help_text='Si se deja vacío cuenta desde el inicio del torneo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues', to='tournament.knockoutround', verbose_name='Contar puntos desde'),
        ),
    ]
