# Generated by Django 6.0.5 on 2026-06-01 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Código')),
                ('flag', models.CharField(blank=True, max_length=10, verbose_name='Emoji bandera')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kickoff_time', models.DateTimeField(verbose_name='Fecha y hora')),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Goles local')),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Goles visitante')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En juego'), ('FINISHED', 'Finalizado')], default='PENDING', max_length=15, verbose_name='Estado')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='matches.team', verbose_name='Visitante')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='matches.team', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['kickoff_time'],
            },
        ),
    ]
